name: CI

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: CI on python${{ matrix.python }} via ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.6, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: pip install tox
      - name: Run flake8
        run: tox -e flake8
      - name: Run unit tests
        run: tox -e py3
      - name: Run docs build
        run: tox -e docs
  deps:
    name: Test dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Checkout default branch
        uses: actions/checkout@v3
        with:
          ref: master
          path: teuthology
      - name: virtualenv
        run: |
          pip install --user virtualenv
          virtualenv ./virtualenv
        working-directory: ./teuthology
      - name: Initial bootstrap
        run: ./bootstrap install
        working-directory: ./teuthology
      - name: Move initial repository
        run: mv teuthology teuthology.orig
      - name: Checkout desired ref
        uses: actions/checkout@v3
        with:
          path: teuthology
      - name: Move virtualenv to new checkout
        run: mv ./teuthology.orig/virtualenv ./teuthology/
      - name: Re-run bootstrap
        run: ./bootstrap install
        working-directory: ./teuthology
