name: integration
on:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Test using docker-compose
        run: ./start.sh
        working-directory: ./docs/docker-compose
      - name: Debug containers
        if: ${{ failure() }}
        run: docker container ls --all --format='{{json .}}'
